# Generated by Django 2.2 on 2019-12-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0003_remove_dailyreport_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='clock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clock_reports', to='clock_in_out_app.Clock'),
        ),
    ]
