# Generated by Django 2.2 on 2019-12-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_in_out_app', '0004_dailyreport_clock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='clock',
        ),
    ]
